### ISSUE TITLE
Configuration link broken on Installation page

### ISSUE THREAD

**Issue by n-hebert** [docmost/docs#4]
Hello

On https://docmost.com/docs/installation/, the Configuration link routes to `https://docmost.com/docs/installation/self-hosting/configuration`, a 404.

A fix could be as simple as changing `./` to `../`, but locally, when running the `yarn start`, the link actually does work, so I was going to push a fix but there may be something worth aligning between dev and prod first, so I thought to open the issue to chat it out a bit.

**Comment by Philipinho** [comment]
Would you like to send a PR?

**Comment by Philipinho** [comment]
Fixed.
